import 'package:flutter/material.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'pip_controller.dart';

class PipOverlay extends StatelessWidget {
  const PipOverlay({super.key});

    @override
      Widget build(BuildContext context) {
          return ListenableBuilder(
                listenable: PipController.instance,
                      builder: (context, _) {
                              final controller = PipController.instance;

                                      if (!controller.isPipActive || controller.videoController == null) {
                                                return const SizedBox.shrink();
                                                        }

                                                                return Positioned(
                                                                          left: controller.position.dx,
                                                                                    top: controller.position.dy,
                                                                                              child: GestureDetector(
                                                                                                          onPanUpdate: (details) => controller.updatePosition(details.delta),
                                                                                                                      child: Material(
                                                                                                                                    elevation: 10,
                                                                                                                                                  borderRadius: BorderRadius.circular(12),
                                                                                                                                                                clipBehavior: Clip.antiAlias,
                                                                                                                                                                              child: Container(
                                                                                                                                                                                              width: 220,
                                                                                                                                                                                                              height: 124,
                                                                                                                                                                                                                              color: Colors.black,
                                                                                                                                                                                                                                              child: Stack(
                                                                                                                                                                                                                                                                children: [
                                                                                                                                                                                                                                                                                    Video(controller: controller.videoController!),
                                                                                                                                                                                                                                                                                                        Positioned(
                                                                                                                                                                                                                                                                                                                              top: 4,
                                                                                                                                                                                                                                                                                                                                                    right: 4,
                                                                                                                                                                                                                                                                                                                                                                          child: IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                  icon: const Icon(Icons.close, color: Colors.white, size: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () => controller.disablePip(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              